env:
  browser: true

settings:
  react:
    version: 'detect'

parserOptions:
  project:
    - ./tsconfig.json

extends:
  - ../.eslintrc.yml
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended

rules:
  react/jsx-no-bind:
    - error
    - ignoreRefs: true
  react/jsx-curly-brace-presence:
    - error
    - never
  react/self-closing-comp:
    - error
  react/jsx-boolean-value:
    - error

overrides:
  - files:
      - vite.config.ts
    rules:
      import/no-default-export:
        - off
  - files:
      - vite-env.d.ts
    rules:
      unicorn/prevent-abbreviations:
        - off
  - files:
      - index.d.ts
    rules:
      unicorn/prevent-abbreviations:
        - off
