extends:
  - stylelint-config-standard-scss
  - ../.stylelintrc.yml

plugins:
  - stylelint-scss

overrides:
  - files: './src/libs/components/checkout/styles.scss'
    rules:
      selector-class-pattern: null
      declaration-no-important: null
